version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing Node.js version 18..."
      - echo "Node version:"
      - node -v
      - echo "NPM version:"
      - npm -v

  pre_build:
    commands:
      - echo "Entering pre_build phase..."
      # Use npm ci for clean, reproducible installs based on package-lock.json
      - echo "Installing application dependencies using npm ci..."
      - npm ci

  build:
    commands:
      - echo "Entering build phase..."
      # Run linting
      - echo "Running linter..."
      - npx ng lint  # <-- Add npx here
      # Run tests (if enabled)
      # - echo "Running unit tests..."
      # - npx ng test --watch=false --browsers=ChromeHeadless # <-- Add npx here if using tests
      # Build the Angular application
      - echo "Building Angular application for production..."
      - npx ng build --configuration production # <-- Add npx here
      - echo "Build completed on `date`"

  post_build:
    commands:
      - echo "Entering post_build phase..."
      - echo "Build process finished."

artifacts:
  # Adjust the base-directory based on your angular.json's outputPath
  # For Angular 17+ with default 'application' builder, it's typically:
  base-directory: dist/modern-calculator/browser
  files:
    - '**/*'

# cache: # Optional: Uncomment to cache node_modules for potentially faster builds
#   paths:
#     - 'node_modules/**/*'